version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: catfetch
    main: ./cmd/catfetch
    binary: catfetch
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    # Note: macOS builds require a macOS runner due to CGO + cross-compilation complexity
    # To add macOS builds, use a matrix strategy with macos-latest runner

archives:
  - id: catfetch-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: bmj2728
    name: catfetch
  draft: false
  prerelease: auto
